# Generated by Django 5.0.6 on 2024-06-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_subheader',
            new_name='subheader',
        ),
    ]
