# Generated by Django 5.0.6 on 2024-06-26 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_company_alter_jobhistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.company'),
        ),
    ]
