# Generated by Django 5.0.6 on 2024-06-26 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_jobhistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.company'),
        ),
    ]
