# Generated by Django 5.0.6 on 2024-06-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_jobhistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.company'),
        ),
    ]
