# Generated by Django 5.0.6 on 2024-06-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_company_about_alter_jobhistory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_profile_icon.png', null=True, upload_to='profile_images/'),
        ),
    ]
