# Generated by Django 5.0.6 on 2024-06-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image',
            field=models.ImageField(blank=True, default='company_images/default_company_icon.png', null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='eduhistory',
            name='school_image',
            field=models.ImageField(blank=True, default='school_images/default_school_icon.png', null=True, upload_to='school_images/'),
        ),
    ]
