# Generated by Django 5.0.6 on 2024-06-24 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_header', models.CharField(max_length=30)),
                ('profile_subheader', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('about', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('date_start', models.DateField(verbose_name='Start Date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EduHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_school', models.CharField(max_length=30)),
                ('name_major', models.CharField(max_length=30)),
                ('date_start', models.DateField(verbose_name='Start Date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
