# Generated by Django 5.0.6 on 2024-06-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_jobhistory_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='header',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subheader',
            new_name='headline',
        ),
    ]
